export const userdata = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    phone: "1234567890",
    joiningDate: "2022-01-01",
    bio: "Software Engineer",
    department: "Sales",
    position: "Manager",
    basicSalary: 5000,
    allowances: 1000,
    deductions: 500,
    email: "LZ5wz@example.com",
    role: "admin",
  },
  {
    id: 2,
    firstName: "Hamza",
    lastName: "hayat",
    phone: "1234567890",
    joiningDate: "2022-01-01",
    bio: "Software Engineer",
    department: "Marketing",
    position: "Manager",
    basicSalary: 5000,
    allowances: 1000,
    deductions: 500,
    email: "LZ5wz@example.com",
    role: "admin",
  },
];

export const leaveData = [
  {
    id: 1,
    user: {
      id: 1,
      name: "John Doe",
    },
    type: "Sick Leave",
    duration: {
      from: "2026-04-01",
      to: "2026-04-10",
    },
    totalDays: 3,
    reason: "Fever",
    status: "Pending",
    createdAt: "2022-01-10",
    approvedBy: null,
  },
];

export const payslipData = [
  {
    id: 1,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "february",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
  {
    id: 5,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "March",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
  {
    id: 6,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "April",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
  {
    id: 2,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "september",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
  {
    id: 3,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "september",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
  {
    id: 4,
    user: {
      id: 1,
      name: "John Doe",
    },
    period: "september",
    basicSalary: 5000,
    netSalary: 10000,
    status: "paid",
    createdAt: "2022-01-01",
  },
];

export const tasks = [
  {
    id: 1,
    assignee: {
      id: 1,
      name: "John Doe",
    },
    title: "make a website",
    description: "Description of Task 1",
    status: "Pending",
    priority: "High",
    deadline: "2022-01-01",
    createdAt: "2022-01-01",
    progress: 50,
  },
  {
    id: 2,
    assignee: {
      id: 1,
      name: "Hamza Hayat",
    },
    title: "make a dashboard",
    description: "Description of Task 1",
    status: "Completed",
    priority: "High",
    deadline: "2022-01-01",
    createdAt: "2022-01-01",
    progress: 20,
  },
  {
    id: 2,
    assignee: {
      id: 1,
      name: "Hamza Hayat",
    },
    title: "make a dashboard",
    description: "Description of Task 1",
    status: "Completed",
    priority: "High",
    deadline: "2022-01-01",
    createdAt: "2022-01-01",
    progress: 20,
  },
  {
    id: 2,
    assignee: {
      id: 1,
      name: "Hamza Hayat",
    },
    title: "make a dashboard",
    description: "Description of Task 1",
    status: "Completed",
    priority: "High",
    deadline: "2022-01-01",
    createdAt: "2022-01-01",
    progress: 20,
  },
  {
    id: 2,
    assignee: {
      id: 1,
      name: "Hamza Hayat",
    },
    title: "make a dashboard",
    description: "Description of Task 1",
    status: "pending",
    priority: "High",
    deadline: "2022-01-01",
    createdAt: "2022-01-01",
    progress: 20,
  },
];
